- name: Create user in Ubuntu 22.04
  hosts: all
  become: yes
  tasks:
    - name: Create ansible user
      user:
        name: ansible
        create_home: true
        shell: /bin/bash
        comment: "Ansible Management Account"
        expires: -1
        password: "{{ 'DevOps@2020' | password_hash('sha512','A512') }}"

    - name: Ensure PasswordAuthentication is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify: Restart SSH service

    - name: Add ansible user to sudoers with NOPASSWD
      lineinfile:
        path: /etc/sudoers
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

  handlers:
    - name: Restart SSH service
      service:
        name: ssh
        state: restarted