- hosts: kubernetes
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      tags: 
        - install

    - name: Copy the index.html file
      copy:
        src: index.html
        dest: /var/www/html/index.html
      notify:
        - start the service
      tags:
        - web

    - name: Debug message
      debug:
        msg: "completed the tasks"
      tags:
        - debug

  handlers:      
    - name: start the service
      service:
        name: apache2
        state: started
      tags:
        - service
