- hosts: docker
  become: true
  tasks:
  - name: update
    apt: update_cache=yes

 - name: Install NGINX
    apt:
     name: nginx
     state: present

  - name: copy the config file to default
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/sites-available/default
      mode: 0644
    notify:
    - restart the nginx service

  - name: Enable default Nginx website
    file:
      src: /etc/nginx/sites-available/default
      path: /etc/nginx/sites-enabled/default
      state: link

  - name: copy the index.html file
    template:
      src: index.html
      dest: /var/www/html/
    notify:
    - restart the nginx service

  - name: Start and Enable NGINX Service
    service:
      name: nginx
      state: started
      enabled: yes

  handlers:
  - name: restart the nginx service
    service:
      name: nginx
      state: restarted
