- hosts: kubernetes
  become: yes
  tasks:
  - name: add jenkins GPG key
    shell:
      curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
    args:
      creates: /usr/share/keyrings/jenkins-keyring.asc

  - name: Add Jenkins repository to sources list
    shell:
      echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
    args:
      creates: /etc/apt/sources.list.d/jenkins.list

  - name: Update the server
    apt:
     update_cache: yes

  - name: install java 21
    apt:
      name: openjdk-21-jdk
      state: present

  - name: install java 11
    apt:
      name: openjdk-11-jre
      state: present

  - name: install jenkins
    apt:
      name: jenkins
      state: present

  - name: enable jenkins
    systemd:
      name: jenkins
      enabled: yes 

  - name: Start jenkins
    service:
      name: jenkins
      state: started

  - name: sleep for 330 sec and continue playbook
    wait_for:
      delay: 30

  - name: Print Jenkins status
    debug:
      msg: "Jenkins service is running"

  - name: init password for jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: result

  - name: print init password jenkins
    debug:
      var: result.stdout